### ISSUE TITLE
This mod does nothing

### ISSUE THREAD

**Issue by ProfessorBustanut** [ArtixAllMighty/JustFashion#15]
how do you use this? it dosnt add any items and there's no new buttons to click there's nothing in jei and there's nothing in the controls as far as i can see installing this mod did nothing and yes i downloaded and installed the resource pack i even downloaded the library mod the page didnt say it required

**Comment by AbsolemJackdaw** [comment]
after installing the mod, and runing it once, having the resource pack selected in-game, a restart of the game is advised so the mod can detect the pack as well. because of how mods load and resource packs work, it is not something I can change. 

After that, no items or blocks are requiered. you can open the gui by key press. default is likely to be inactive, or conflicting, so the end user has to bind a key in keybinds to be able to open the GUI and use the mod

let me know if it still doesn't work after that ! thank you

**Comment by AbsolemJackdaw** [comment]
I'm going to close this issue because the author didn't get back after I posted a solution, which I assume worked.
