### ISSUE TITLE
The game crashes and exits when dying in a world

### ISSUE THREAD

**Issue by sepsol** [ArtixAllMighty/JustFashion#9]
I don't understand crash reports but from the latest.log I suspected that it might be from Just Fashion. If not, please guide me in the right direction to report this issue to the respective developers of the troubling mod. Here are some useful files:

[crash-2019-10-31_12.19.30-client.txt](https://gist.github.com/SepSol/b0a2785ed951fb7b285456fd39b1844c)
[diagnostic.log](https://gist.github.com/SepSol/d2bb8e33ecc4401642f5fdb71a0d9066)
[debug.log](https://gist.github.com/SepSol/ff2172de8aa52011eb66629b60130a26)
[latest.log](https://gist.github.com/SepSol/407232e878c49bfefdaab81cb2833132)

**My specs:**
- Minecraft 1.14.4
- Forge 28.1.70
- OptiFine HD U F4
- JustFashion-1.14.4-2.1.0.2

**Steps to reproduce:**
1. open the game
2. create a new world
3. die
4. game crashes with exit code of -1 (0xffffffff) before allowing you to choose 'respawn'
5. now launch the game again and select 'respawn' to continue playing

**Comment by Fuzss** [comment]
Player is still being rendered as a paper doll on screen by my Console Experience mod even after death (in the background of the death screen). This triggers a crash in both your HandleRenderSwap#swapRenders and HandleRenderSwap#resetRenders due to the data variable being null. 

I guess this is the case due to your capability being null, at least that's what's being returned by FashionData#get.

So a quick fix would obviously be to add a null check in both methods mentioned above. For the underlaying issue (your capability being null when the player is dead) if have no idea so far.

**Comment by sepsol** [comment]
That got really technical! I still don't understand what is being null and what does a null check do to fix this, but that's probably because I don't know programming. :)

**Comment by AbsolemJackdaw** [comment]
luckily for you guys i'm currently fixinga bunch of bugs, and i fixed this one before i read the bug report ! 
thanks for the report, will soon close this with the commit

**Comment by AbsolemJackdaw** [comment]
@Fuzss no need for null checks, i'm just not handling the capability correctly. it needs to be an optional, and that is non nullable; when using ifpresent. if ts not present (null) it will just do nothing. check updated code to get an idea of what i mean.

**Comment by sepsol** [comment]
That's awesome! Thanks a lot :)
